### ISSUE TITLE
Use XSLT to add support for properly describing delta functions

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-metadata#114]
Delta functions need to have annotations added to signal that they will return `@Odata.DeltaLink` and `@OData.NextLink` in the response payload.

We need to identify how to annotation the functions properly.

**Comment by baywet** [comment]
Closing at this is added by convention by the conversion library. BaseDeltaFunctionResponse has the deltalink and nextlink properties
