### ISSUE TITLE
Deleted items is missing derived type constraints to generate the additional odata cast path segments

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#126]
[this endpoint](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http) can only be used with a type cast segment.
Now that our pipelines are updates to the latest version of the conversion library, we should insert the required derived type constraint annotation.

**Comment by ddyett** [comment]
Blocks fixes for GO SDK.

**Comment by irvinesunday** [comment]
@baywet the metadata has the `DerivedTypeConstraint` annotation for `deletedItems`. 

![image](https://user-images.githubusercontent.com/40403681/158851842-2e7edb0b-9653-4dbe-ac0f-252da0ce9ede.png)

**Comment by baywet** [comment]
Thanks for looking into this. The annotation looks correct.
The default values in the conversion lib look correct as well.
https://github.com/microsoft/OpenAPI.NET.OData/blob/5c8ef30936d3c908aae1df022674ff8d1a4c7b56/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L199
https://github.com/microsoft/OpenAPI.NET.OData/blob/5c8ef30936d3c908aae1df022674ff8d1a4c7b56/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L204

And hidi is not setting those.
https://github.com/microsoft/OpenAPI.NET/blob/33a573b4ebeb1361bdea750467e2b28625021018/src/Microsoft.OpenApi.Hidi/OpenApiService.cs#L295

So something must be wrong in the conversion lib itself, could you have a deeper look into this please?

**Comment by irvinesunday** [comment]
Here's the issue: https://github.com/microsoft/OpenAPI.NET.OData/issues/199

**Comment by baywet** [comment]
also merged https://github.com/microsoft/OpenAPI.NET/pull/852 so we see the changes in the weekly pipeline, preparing a release soon
