### ISSUE TITLE
The function name is incorrect: Get-MgDeviceManagementDeviceCustomAttributeShellScriptUserRunStateDeviceRunStateManagedDeviceCloudPcRemoteActionResult

### ISSUE THREAD

**Issue by AshleyYangSZ** [microsoftgraph/msgraph-metadata#133]
Issue found by this https://twitter.com/alexandair/status/1504088670718017537?t=Ze2i48cMhOHxyn202NCjjA&s=19 
And the link to the doc: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.devicemanagement.functions/get-mgdevicemanagementdevicecustomattributeshellscriptuserrunstatedevicerunstatemanageddevicecloudpcremoteactionresult?view=graph-powershell-beta

`Get-MgDeviceManagementDeviceCustomAttributeShellScriptUserRunStateDeviceRunStateManagedDeviceCloudPcRemoteActionResult`

This should be  `Get-MgDeviceManagementManagedDeviceCloudPcRemoteActionResult`

**Comment by AshleyYangSZ** [comment]
Hi @peombwa Thanks for you explanation, since I'm not the owner of  the two metadata, could we move forward with the second option? _Alternatively, we can apply an XSLT transform to remove the ContainsTarget="true" as a temporary fix firstly?
![image](https://user-images.githubusercontent.com/72924235/169051880-7236309e-beec-47db-95f5-92540b15b796.png)

**Comment by peombwa** [comment]
We should also remove the following unsupported paths/commands:
![image](https://user-images.githubusercontent.com/72924235/169050002-790350e2-6177-4c58-9ee7-556b8b1645e6.png)
![image](https://user-images.githubusercontent.com/72924235/169050353-091b910d-9975-4d87-9e4e-3cbb282b260f.png)

Only the commands highlighted in yellow are supported.

Related to https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1221#issuecomment-1130019432.

**Comment by peombwa** [comment]
Closed by https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/1.10.0
