### ISSUE TITLE
Java code generation issue

### ISSUE THREAD

**Issue by PongPong** [microsoftgraph/msgraph-metadata#14]
I tried to generate java classes for MS graph beta API with the following command , 

.\scripts\runTypewriter.ps1 -verbosity Info -metadata https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_beta_metadata/cleanMetadataWithDescriptionsbeta.xml -output .\temp -generationMode Files -cleanup $false -l Java  

however, it generate a huge amount of java classes (> 13k), which leads to slow compilation, are there any ways to exclude unused classes?
![image](https://user-images.githubusercontent.com/1247179/77378403-d301be80-6db0-11ea-88e1-fb72072e2ae6.png)

Regards
Pong

**Comment by MIchaelMainer** [comment]
This is the current state of our generation. We have work to do on this.

**Comment by baywet** [comment]
Hey @PongPong 
Thanks for reaching out and sorry for the delay in the answer.
Is this still something you're looking into?
If you're using the java project, I upgraded gradle and made a set of changes that make the compilation faster than it used to be.

**Comment by PongPong** [comment]
@baywet 
 Appreciate your glorious efforts, this will unquestionably speed up our development, however, our IDE IntelliJ notwithstanding take expanded time to index so plentiful classes.

**Comment by baywet** [comment]
We have plans to stop generating part of the interfaces we generate in an effort to reduce the number of symbols overall and because they are only used for one implementation. That'd be a breaking change and it's a longer term change at this point.

**Comment by baywet** [comment]
FYI the work I was mentioning is in progress over [here](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/311) if you want to follow along.
I'm going to go ahead and close this issue as there's no action to be taken besides waiting for the v3 work to complete.
