### ISSUE TITLE
New-MgDeviceManagementImportedDeviceIdentity - Error

### ISSUE THREAD

**Issue by VGRMike** [microsoftgraph/msgraph-metadata#147]
I am trying to use the cmd New-MgDeviceManagementImportedDeviceIdentity  to insert new serialnumbers from our assetDB.
connect-mggraph works fine, using certificate and appID.

My testing example (serial is fakeserial, but valid):
 $NewID = New-Object  Microsoft.Graph.PowerShell.Models.MicrosoftGraphImportedDeviceIdentity
 $NewID.Description = "A Description"
 $NewID.ImportedDeviceIdentifier = "07C200200007"
 $NewID.ImportedDeviceIdentityType = "serialNumber"

I then run the command
New-MgDeviceManagementImportedDeviceIdentity -BodyParameter $NewID

The error i receive looks like this.
New-MgDeviceManagementImportedDeviceIdentity : No OData route exists that match template ~/singleton/navigation with http verb POST for request /DeviceEnrollmentFE_2204/StatelessDeviceEnrollmentFESe
rvice/deviceManagement/importedDeviceIdentities.

**Comment by VGRMike** [comment]
Thanks for the reply.
Tried your suggestion, (and corrected ImportedDeviceIdentifierType  to ImportedDeviceIdentityType) but this generated a new error ( I will post a ticket as suggested): 
_Import-MgDeviceManagementImportedDeviceIdentityList : Unable to cast object of type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonObject' to type 'Microsoft.Graph.PowerShell.Runtime.Json.JsonArray'.
At line:11 char:1
+ Import-MgDeviceManagementImportedDeviceIdentityList -ImportedDeviceId ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-MgDevice..._ImportExpanded], InvalidCastException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.ImportMgDeviceManagementImportedDeviceIdentityList_ImportExpanded_

**Comment by peombwa** [comment]
Closing as service issue - https://github.com/microsoftgraph/microsoft-graph-docs/issues/14047.

See response at https://learn.microsoft.com/en-us/answers/questions/834546/adding-serialnumbers-using-new-mgdevicemanagementi for alternative command/API.
