### ISSUE TITLE
Get-MGChatMessage: using FILTER throws "query specified in the URI is not valid. Query option 'Filter' is not allowed."

### ISSUE THREAD

**Issue by mbourgon** [microsoftgraph/msgraph-metadata#152]
I am trying to filter chats looking for recent messages, rather than doing a FOREACH on the 1000+ chats I've been in (get-mgchat -all -pagesize 50) and running a WHERE clause on the results. But using FILTER doesn't appear to work.

get-mgchatmessage -ChatId 19:deadbeeff49d88d4455f5279e5d8b@thread.v2 -filter "CreatedDateTime ge 2022-05-11"

gives: 
Get-MgChatMessage_List: The query specified in the URI is not valid. Query option 'Filter' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.

I can't really find anything on how to change that setting with powershell/cmdlets, and the doc page for get-mgchatmessages says Filter is supported. Thanks.

**Comment by mbourgon** [comment]
@peombwa  thanks for the explanation, and for allowing me to waste your time.  

Is there somewhere I can ask related questions about Graph & PoSH? For instance, is there any other way to filter? Like I see that chatmessage delta supports filter for the lastModifiedDateTime; I can use that, so I may crack open the code for that cmdlet to see if there's a way to do it there, but maybe there's already a better way?

**Comment by ddyett** [comment]
@maisarissi any forum you'd recommend else I think we can close this issue as capability annotations is a broader tracked stream.

**Comment by peombwa** [comment]
Sorry for the late response to this.

https://developer.microsoft.com/en-us/graph/support is the right forum for Microsoft Graph API Q&A.

Consolidating the issue https://github.com/microsoftgraph/msgraph-metadata/issues/298.
