### ISSUE TITLE
Remove-MgAgreementAcceptance failing to run

### ISSUE THREAD

**Issue by BenHagueNZ** [microsoftgraph/msgraph-metadata#155]
I can run "Get-MgAgreementAcceptance -AgreementId <agreementid>" to get the acceptances of that agreement. However running "Remove-MgAgreementAcceptance -AgreementAcceptanceId <agreementacceptanceid> -AgreementId<agreementid>" with an id from the first step and the same agreement id gives the error: 
Remove-MgAgreementAcceptance : No HTTP resource was found that matches the request URI 
'https://api.termsofuse.identitygovernance.azure.com/v2.0/agreements('<agreementid')/acceptances('<agreementacceptanceid')?x-scenario=MSGraph&x-tenantid=[tenantId]'.
At line:1 char:1
+ $agreementAcceptance |Remove-MgAgreementAcceptance
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ IfMatch =  }:<>f__AnonymousType82`1) [Remove-MgAgreem...leteViaIdentity], RestException`1
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.RemoveMgAgreementAcceptance_DeleteViaIdentity
(NB: [tenantId] is as it appears in the error message.
I get the same error contructing a hash and passing it to the function.
I can find very little documentation around this function, am I calling it incorrectly, or is there an issue with the function?

**Comment by ddyett** [comment]
closing this one as we can't act.
