### ISSUE TITLE
Get-MgUserMessage is missing the -Expand/-ExpandProperty argument

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/msgraph-metadata#168]
Found it odd that Get-MgUserMailFolderMessage has -Expand/-ExpandProperty, but the core cmdlet, Get-MgUserMessage, does not. Using Invoke-MgGraphRequest as a workaround for now.

**Comment by peombwa** [comment]
Created an ICM with the workload for this to be resolved.

ICM #336830893
