### ISSUE TITLE
Path for Commit Action not present in openApi document

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-metadata#179]
The path for the `commit` action bound to the `graph.mobileAppContentFile` type is not present in the generated openApi document. This probably is because we currently do not generate paths from NavigationProperties that result from derived type constraint due to bottlenecks addressed at https://github.com/microsoft/OpenAPI.NET/pull/868

```xml
<Action Name="commit" IsBound="true">
  <Parameter Name="bindingParameter" Type="graph.mobileAppContentFile" />
  <Parameter Name="fileEncryptionInfo" Type="graph.fileEncryptionInfo" />
</Action>
```

This leads to the `FileEncryptionInfo` type not being referenced in any path in the generated document and not being present in the generated SDKs

**Comment by dansmitt** [comment]
@andrueastman any updates?

**Comment by garport** [comment]
@andrueastman its been 3 months with no update on this. We are still stuck on version 4 of the Graph API. Any updates?

**Comment by dansmitt** [comment]
@andrueastman ?

**Comment by ranjith279** [comment]
@andrueastman any updates , waiting for a new version?

**Comment by andrueastman** [comment]
This issue was being followed up via https://github.com/microsoft/OpenAPI.NET.OData/issues/269 and we will be looking to enable the appropriate settings in the conversion library once we validate the newly introduced paths in the reference document do not have any unintended side effects with the downstream tooling due to the increasing size of the metadata.

**Comment by dansmitt** [comment]
@andrueastman any updates after 6 months?

**Comment by svrooij** [comment]
@dansmitt I know this it not a solution, but if you want to migrate to the v5 SDK, you can use extension methods to fill the gap.

https://github.com/svrooij/WingetIntune/blob/26d6ade5e2ed8a1094c4117e6cfdc7cb68ef0050/src/WingetIntune/Graph/GraphServiceClientExtensions.cs#L92-L112
