### ISSUE TITLE
Get-MgGroupMember missing ConsistencyLevel parameter for search query

### ISSUE THREAD

**Issue by ArmaanMcleod** [microsoftgraph/msgraph-metadata#185]
When running `Get-MgGroupMember` with a search query like below:

```pwsh
Get-MgGroupMember -GroupId "<group_id>" -Search "Id: <id>"
```

You get the following error:

```
Get-MgGroupMember_List: Request with $search query parameter only works through MSGraph with a special request header: 'Consistency: eventual'
```

Unlike other cmdlets, there doesn't seem to be a `-ConsistencyLevel eventual` option to set this easily. Also checked the documentation: https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroupmember?view=graph-powershell-1.0 and it doesn't seem to be there either.

Filter queries like below works fine:

```pwsh
Get-MgGroupMember -GroupId "<group_id>" -Filter "Id eq '<id>'"
```

**Comment by peombwa** [comment]
Closing as resolved.

`-ConsistencyLevel` is now supported as a parameter on the command. See https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.groups/get-mggroupmember?view=graph-powershell-1.0.
