### ISSUE TITLE
Add `insertRestrictions` and `UpdateRestrictions` to `AdministrativeUnit` non-containment nav. property in the CSDL

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/msgraph-metadata#200]
This will facilitate the generation of POST and PUT/PATCH operations for this non-containment navigation property.

**Comment by darrelmiller** [comment]
In addition to the team updating their metadata, we are dependent on this enhancement https://github.com/microsoft/OpenAPI.NET.OData/issues/265 to OpenApi.Net.Odata
