### ISSUE TITLE
The itemAnalytics properties for site and drive item should have a ContainsTarget="true" attribute

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#201]
Workload: OSDP
Original report: https://github.com/microsoftgraph/msgraph-sdk-java/pull/1155
Impact: analytics properties on site and drive item (v1 and beta)

**Comment by baywet** [comment]
Incident created https://portal.microsofticm.com/imp/v3/incidents/details/330203089/home

**Comment by Jatish-Khanna** [comment]
is there any progress on this issue?

**Comment by baywet** [comment]
Thanks for the reminder, the ICM got stuck in the system because the person it has been routed to is OOO. I've looped in additional people from that team.

**Comment by Jatish-Khanna** [comment]
The issue has been closed, is it fixed?

**Comment by baywet** [comment]
no as far as I know, the metadata is still inaccurate. If you want to speed up the process, please open a support case with a production tenant and provide them this ICM number (comment from august 25)
