### ISSUE TITLE
Update metadata collection process to use metadata in Schemas folder instead of livesite

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-metadata#203]
In order to get the most up to date and unfiltered metadata for our SDKs/GraphExplorer/OpenAPI Generation we need to use the metadata in the schemas folder and not the metadata at the $metadata endpoint.  Changing the script below should solve this problem.

https://github.com/microsoftgraph/msgraph-metadata/blob/5ffafe30ccd4bec02904d9abb5f96d41b29a9bcd/scripts/downloadDiff.ps1#L32-L38

**Comment by irvinesunday** [comment]
We would actually need to update the below MSGraph-SDK-Code-Generator scripts:

- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/0a4e268ecaca5f6b978375657cb40e754d71c7ad/.azure-pipelines/generation-pipeline.yml#L156-L157C3
- https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/.azure-pipelines/generation-templates/capture-metadata.yml

**Comment by irvinesunday** [comment]
Switched `beta` first to test and validate with SDKs before switching `v1.0`
