### ISSUE TITLE
XSLT transform or code generator adds unnecessary baseType to complexTypes.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#22]
It looks like we are adding a base type to a complex type that shouldn't have one.

According to the [live metadata](https://graph.microsoft.com/beta/$metadata), `chatMessageMention` is a complex type with no base type, but in the [clean metadata](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_v10_metadata/cleanMetadataWithDescriptionsv1.0.xml), we seem to be adding a base type of `entity` to it. This leads to a property conflict since both `entity` and `chatMessageMention` have an `id` property of different types, a `string` for `entity` and  `int32` for  `chatMessageMention`.

#### Live Metadata
![image](https://user-images.githubusercontent.com/7061532/83090615-05989380-a04e-11ea-9821-22ef18466e78.png)
#### Clean Metadata
![image](https://user-images.githubusercontent.com/7061532/83090674-2a8d0680-a04e-11ea-805b-6073f2f0c424.png)

The same applies to the clean v1.0 metadata.

See https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/110#discussion_r431544323

**Comment by darrelmiller** [comment]
@MIchaelMainer  Can this be closed?
