### ISSUE TITLE
`microsoft.graph.directorySetting` is missing a filter restrictions annotation.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#225]
Filtering should be restricted on `/settings` (`microsoft.graph.directorySetting`) as the API does not support `$filter`. Requests with a filter query parameter fail with a 400 `Filtered searches against this resource are not supported`.

**Comment by irvinesunday** [comment]
This was resolved by: https://github.com/microsoftgraph/msgraph-metadata/pull/227
