### ISSUE TITLE
restrictions annotations missing for /teams endpoint

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#237]
The service doesn't support the following call in v1/beta today:
- GET /teams

However, our current OpenAPI description is documenting this operation, leading clients to have an API surface for it, confusing customers.
To be clear, GET /teams/{id} [is supported](https://learn.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=http) and POST /teams [as well](https://learn.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http)

We should add an annotation to the metadata XSL to this operation is not emitted anymore during the conversion process.

**Comment by peombwa** [comment]
@baywet, the service support `GET /teams` in `beta` - https://learn.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&tabs=http. The restrictions annotations should only be applied to the `v1.0` metadata.
