### ISSUE TITLE
`drive` nav property for `site` entityType should have `ContainsTarget="true"` attribute

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#238]
The ODSP API supports uploading of files to a site's default document library via `PUT /sites/{site-id}/drive/items/{item-id}/content`. This path is currently missing in the OpenAPI document due to missing `ContainsTarget="true"` attribute on `drive` nav property in the clean metadata.

See https://learn.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http#http-request-to-replace-an-existing-item.

**Comment by baywet** [comment]
I disagree, drive has a root collection of drives. Hence it's not contained.
