### ISSUE TITLE
Remove containment on `singleValueExtendedProperties` and `multiValueExtendedProperties` nav properties

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#246]
The CSDL metadata wrongly describes `singleValueExtendedProperties` and `multiValueExtendedProperties` as contained nav properties.

As per the API reference, the nav properties can only be:
1. Created or updated in POST and PATCH bodies of the host resource type - https://learn.microsoft.com/en-us/graph/api/multivaluelegacyextendedproperty-post-multivalueextendedproperties?view=graph-rest-1.0.
2. Read via `$expand` on a resource instance - https://learn.microsoft.com/en-us/graph/api/multivaluelegacyextendedproperty-get?view=graph-rest-1.0.

Calls to `/me/messages/{id}/multiValueExtendedProperties` will always fail with a `405 (Method Not Allowed) - the OData request is not supported`.

**Comment by irvinesunday** [comment]
We basically need to set navigability of the mentioned nav. properties to `Org.OData.Capabilities.V1.NavigationType/None`
