### ISSUE TITLE
inacurracies in contains target for drive, drive item and workbook

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#248]
related to #247 
related to https://github.com/microsoft/OpenAPI.NET.OData/issues/327

A few corrections are required:
- [x] drives property on user and group should be contains target false, because there is a drives entity set
- [x] root property on driveItem should be contains target false, because it's a shorthand to .../items/{id}
- [x] analytics property on driveitem should be true, because there's no other way to access it
- [x] listItem property on driveItem and sharedDriveitem should be false, because there it a lists entity set and list items canonical path is on the list
- [x] remove the drive singleton, because it's just a shorthand to /sites/tenant.onmicrosoft.com/drive, and singleton expand all contained targets, which leads to an explosion of paths
- [x] worksheet property on workbooktable, workbookrange, workbooknameditem, workbookchart and workbookpivottable should be false, because they are all back properties to the parent worksheet which already contains them.
- [x] remove the workbooks entity set as the service never supported it.
- [x] remove the annotation target microsoft.graph.driveItem/workbook or type Org.OData.Capabilities.V1.NavigationRestrictions

By implementing those changes Darrel and I we able to add all the excel stuff WHILE reducing overall description size:
- before changes: 28M
- after changes (with the restriction): 24.7M
- after all changes: 26M

Uploading the diff file as a backup for my description
[MetadataFixes.txt](https://github.com/microsoftgraph/msgraph-metadata/files/10428367/MetadataFixes.txt)

**Comment by peombwa** [comment]
- [ ] `children` nav property on `driveItem` should have InsertRestrictions with `insertable` of `true`. See [create folder API reference](https://learn.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http#http-request).
