### ISSUE TITLE
version in the OpenAPI descriptions is incorrect

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#275]
The version field of the OpenAPI description is currently being set to a random number instead of the true version (v1.0|beta).
This is [causing issues for indexers](https://github.com/APIs-guru/openapi-directory/issues/1053) and might be confusing to consumers of the description.
We should address this in the generation process to correct that information.

Once this is fixed, please revert to the issue linked to give a heads up to maintainers.

**Comment by irvinesunday** [comment]
@baywet this sounds like a conversion issue. Should we move it to the relevant repository?

**Comment by baywet** [comment]
You are correct, the conversion library reads the information from the odata context.
https://github.com/microsoft/OpenAPI.NET.OData/blob/a8d815a19f8feae41c55fc66779d25d26ef7eb78/src/Microsoft.OpenApi.OData.Reader/Generator/OpenApiInfoGenerator.cs#L29

And that comes from the version in the convert settings.

https://github.com/microsoft/OpenAPI.NET.OData/blob/a8d815a19f8feae41c55fc66779d25d26ef7eb78/src/Microsoft.OpenApi.OData.Reader/OpenApiConvertSettings.cs#L28

Transferring.
(once the fix is implemented, we'll need to update the conversion settings)

**Comment by baywet** [comment]
I'm not powerful enough to transfer between orgs. closing this and will reopen on the other side.

**Comment by baywet** [comment]
created this https://github.com/microsoft/OpenAPI.NET.OData/issues/346
