### ISSUE TITLE
beta generation failing because of delta function

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#276]
[beta weekly generation is currently failing](https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_build/results?buildId=106293&view=logs&j=4c81e8e4-6eb9-5def-7261-b44ad0fc1b7d&t=163839c6-f69e-5b5d-39e2-5b38e97d3fe3) because [a delta function on directory objects was added](https://dev.azure.com/msazure/One/_git/AD-AggregatorService-Workloads/pullRequest/7582888#1676991425) which conflicts with the derived types delta functions.

I believe we should introduce an xsl fix that removes the functions on the derived types, only for beta, only for kiota based SDK for the time being until the service fixes their definition to unblock our generation pipeline, but I'm open to feedback here first.

CC @andrueastman @peombwa @irvinesunday

**Comment by peombwa** [comment]
+1 to adding an XSL transform to remove the functions on the derived types (I assume OpenAPI.NET.OData will still add the function to the derived types accordingly). This XSL transform should be applied to all metadata files used by OpenAPI tools (Kiota, DevX, etc.).

**Comment by andrueastman** [comment]
> +1 to adding an XSL transform to remove the functions on the derived types (I assume OpenAPI.NET.OData will still add the function to the derived types accordingly). This XSL transform should be applied to all metadata files used by OpenAPI tools (Kiota, DevX, etc.).

I agree. Implement the transform on the metadata but still eventually make the conversion library resilient to this as this seems to be valid OData according to https://github.com/microsoft/OpenAPI.NET.OData/issues/343#issuecomment-1438940862

**Comment by irvinesunday** [comment]
This is currently affecting `beta`, do we want to be proactive and cover `v1` as well?

**Comment by baywet** [comment]
just beta for the time being since the change hasn't rolled out to v1 at the moment. I suspect it'll eventually come to v1, and we'll update/remove the condition when it does.

**Comment by andrueastman** [comment]
Looks like this one was recently merged(yesterday) so we will need it for v1 as well. 
https://msazure.visualstudio.com/One/_git/AD-AggregatorService-Workloads/pullrequest/7644692

**Comment by baywet** [comment]
closing since the fix is implemented in the conversion lib
