### ISSUE TITLE
openapi.yaml generation is creating duplicated operationIds

### ISSUE THREAD

**Issue by kcphila** [microsoftgraph/msgraph-metadata#289]
I was attempting to use an existing openapi parser ([Azure Autorest](https://github.com/Azure/autorest)) to build a client for the graph yaml, and it generates ~40 errors due to duplicate `operationId` values. And indeed, it is detecting the issue correctly.

For example:

Both of the following have `operationId` values of "Get.Count.sectionGroups-497a":
- `/users/{user-id}/onenote/sectionGroups/$count`
- `/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/$count`

From looking at quite a very of the errors, it appears all (or at least most) of the errors follow this pattern. Based on other entries, it seems like the second element above should have an operation id more like "users.onenote.sectionGroups.count".

**Comment by irvinesunday** [comment]
@kcphila, how about?

`/users/{user-id}/onenote/sectionGroups/{sectionGroup-id}/sectionGroups/$count`  -->
`users.onenote.sectionGroups.sectionGroups.GetCount-497a`

and 

`/users/{user-id}/onenote/sectionGroups/$count`  --->
`users.onenote.sectionGroups.GetCount-497a`
