### ISSUE TITLE
Update open API settings with the version

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-metadata#302]
As a follow up to the version fix in the conversion library we should do these things:
- update the convert settings here to have semversion set to v1.0
- add a script to switch the version to beta.
- call that script in the weekly generation pipeline for beta.

**Comment by irvinesunday** [comment]
This was resolved in this PR: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/985
