### ISSUE TITLE
'Model' query parameter is missing in a few endpoints

### ISSUE THREAD

**Issue by vadrsa** [microsoftgraph/msgraph-metadata#314]
'Model' query parameter is missing in a few endpoints

![228762073-923c4bce-d3bb-4cdb-ac78-005c269daa35](https://user-images.githubusercontent.com/42139078/230291799-dc707846-f4a3-4688-9a7b-3dce5ef18c80.png)

**Comment by peombwa** [comment]
Metered APIs that support `model` payment model should have `model` query parameter via `CustomQueryOption`.

[`CustomQueryOption`](https://oasis-tcs.github.io/odata-vocabularies/vocabularies/Org.OData.Capabilities.V1.html#readrestrictionstype-readrestrictionsbase) is needed to inform clients (SDKs) and downstream tools that the APIs support the query parameter at generation time. The `model` query parameter is used to specify the payment model on an API. See https://learn.microsoft.com/en-us/graph/teams-licenses#payment-models.
