### ISSUE TITLE
POST method missing on route /directory/administrativeUnits/{administrativeUnit-id}/members 

### ISSUE THREAD

**Issue by adamijak** [microsoftgraph/msgraph-metadata#323]
OpenAPI specification misses `POST` method on route `/directory/administrativeUnits/{administrativeUnit-id}/members`, despite it is documented [here](https://learn.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-1.0&tabs=csharp).

I could add member by plain http request.

The result is that proper method is not generated in Graph API client (clients?) microsoftgraph/msgraph-sdk-dotnet#1828 .

**Comment by andrueastman** [comment]
Resolved via https://github.com/microsoftgraph/msgraph-metadata/pull/368
