### ISSUE TITLE
Add `CountRestrictions` annotation and set `Countable=false` for `drives` entity set

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/msgraph-metadata#328]
[/drives/$count](https://graph.microsoft.com/v1.0/drives/$count) is not a valid path. To get the count of drives should be retrieved via: [/drives?$count](https://graph.microsoft.com/v1.0/drives?$count)

Related to: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/2472

**Comment by andrueastman** [comment]
Can we add this path to the list as well?
`https://graph.microsoft.com/v1.0/sites/root/lists/{list-id}/items/$count`

Related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1749

**Comment by irvinesunday** [comment]
> Can we add this path to the list as well? `https://graph.microsoft.com/v1.0/sites/root/lists/{list-id}/items/$count`
> 
> Related to [microsoftgraph/msgraph-sdk-dotnet#1749](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1749)

/sites/{site-id}/lists/{list-id}/items/$count
