### ISSUE TITLE
Add the query parameters to the events delta functions

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-metadata#329]
Related to https://github.com/microsoftgraph/msgraph-sdk-go/issues/318

**Comment by rsitrifork** [comment]
Is there any update on when this might be fixed, or any workaround? The Start and EndDate parameters are required for this API, so it is unusable without being able to set them.

Is there any documentation on how we might be able to contribute the changes to the schema ourselves?
