### ISSUE TITLE
Deleteability should be removed for `profilePhoto` resource type

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#387]
According to [API reference](https://learn.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0#methods), only `GET` and `PUT` are supported on the resource. As such, `DELETE` calls to the resource will fail with a "Method is not allowed".

**Comment by hajekj** [comment]
As of today's [announcement](https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-exchange-online-powershell-userphoto-cmdlets/ba-p/3955744) the `DELETE` method now works. [Documentation](https://learn.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-1.0) doesn't reflect this, but finally can do this via Graph. Thanks!
