### ISSUE TITLE
Missing derived type contraint  annotation for microsoft.graph.sitePage

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-metadata#401]
This causes the missing paths in generated SDKs and would need to be added to unlock 
- The odata cast path `/sites/{site-id}/pages/{page-id}/microsoft.graph.sitePage`
- Nested nativagation properties under the `microsoft.graph.sitePage` type i.e `webParts` and `canvasLayout`

References
- https://learn.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta
- https://learn.microsoft.com/en-us/graph/api/horizontalsection-get?view=graph-rest-beta
- https://learn.microsoft.com/en-us/graph/api/verticalsection-get?view=graph-rest-beta

**Comment by heinrich-ulbricht** [comment]
Does this issue cover the `webpart` endpoints as well?

E.g.

https://learn.microsoft.com/en-us/graph/api/webpart-list?view=graph-rest-beta

Those are missing completely in the Graph Beta SDK for .NET.

**Comment by andrueastman** [comment]
> @andrueastman Does this issue cover the webpart endpoints as well?

Yes this should be case. This should be resolved on the merge of https://github.com/microsoftgraph/msgraph-metadata/pull/546
