### ISSUE TITLE
DeviceAppManagement metadata incomplete

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/msgraph-metadata#420]
There seem the be a lot of relations missing under [App management](https://learn.microsoft.com/en-us/graph/api/resources/intune-app-conceptual?view=graph-rest-beta)

## MobileApps derived types (metadata):

https://github.com/microsoftgraph/msgraph-metadata/blob/86bdaeabf017d1c9f2dd56bd3358a67ad5675185/transforms/csdl/preprocess_csdl.xsl?wt.mc_id=SEC-MVP-5004985#L367-L377

## MobileApps derived types in the docs (missing the endpoints and relations):

- androidLobApp
- win32LobApp

Incorrect metadata means that the [Get win32LobApp](https://learn.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-get?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985#http-request) is incorrect. To get Win32LobApps, you'll need at least a special filter like: `$filter=isof('microsoft.graph.win32LobApp')`

And [creating a Win32LobApp](https://learn.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-create?view=graph-rest-beta&wt.mc_id=SEC-MVP-5004985) does require all the contentFiles and the committing, which is undocumented at the moment.

In [this file](https://github.com/svrooij/WingetIntune/blob/main/src/WingetIntune/Graph/GraphServiceClientExtensions.cs?wt.mc_id=SEC-MVP-5004985) you can see a lot of the endpoints for `win32LobApps` but this list is far from complete I guess.

## MobileApp add category

In the documentation is also no mention of how to add a category to an app, which can be done by posting to `deviceAppManagement/mobileApps/{id}/categories/$ref` like done [here](https://github.com/svrooij/WingetIntune/blob/21e3133b7f0b943661dc671ed22f4be9093e0b86/src/WingetIntune/Graph/GraphServiceClientExtensions.cs?wt.mc_id=SEC-MVP-5004985#L114-L132)

Issue is related to https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2073
@andrueastman I hope I did not miss anything

Unrelated: as an external observer, is there any documentation on the metadata process? Do you start with a pre-generated version based on code and then add additional stuff using xml transformations?
Can we contribute to this as well? How does the build process work? maybe @baywet can elaborate on this topic

**Comment by baywet** [comment]
Thanks for reporting this. Although all the bits are on a public repository, the process is not currently publicly documented as it's fairly complex, orchestrates over a dozen repos, and we generally expect people to make contributions to it. If you want more insights you can [try to parse this file](https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/.azure-pipelines/generation-pipeline.yml)

But we do welcome contributions, this one is fairly trivial that you could take it on, would you mind adding the missing entries?

For the missing documentation for the categories, can you open a separate issues in the docs repository please?
