### ISSUE TITLE
Restriction annotations are missing for `/invitations`

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-metadata#427]
The API only supports `POST /invitations` in v1.0 and beta - https://learn.microsoft.com/graph/api/resources/invitation?view=graph-rest-1.0#methods. However, the current OpenAPI description describes the path as supporting CRUD operations, which is misleading to customers as pointed out at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2290:
<img width="289" alt="image" src="https://github.com/microsoftgraph/msgraph-metadata/assets/7061532/ee884923-dd55-41e6-ad21-d20cce0b383a">

Restriction annotations should be added to the metadata XSL to remove the unsupported operations.

**Comment by irvinesunday** [comment]
I'm curious here. Access to the navigation property `invitedUser` via key is also not supported? _invitations/{invitation-id}/invitedUser_

**Comment by irvinesunday** [comment]
An `IndexableByKey` annotations will need to be added under the `invitations` entity set

```XML
<Annotations Target="microsoft.graph.GraphService/invitations">
   <Annotation Term="Org.OData.Capabilities.V1.IndexableByKey" Bool="false" />
</Annotations>
```
