### ISSUE TITLE
/serviceProvisioningErrors missing for user, group and orgcontact entities

### ISSUE THREAD

**Issue by SteveMutungi254** [microsoftgraph/msgraph-metadata#428]
The following paths:

/user/serviceProvisioningErrors
/group/serviceProvisioningErrors
/orgContact/serviceProvisioningErrors

are missing on the metadata repo, which is necessary for the PowerShell cmdlet generation.

The APIs (both `beta` and `v1.0` are already publicly available.

**Comment by irvinesunday** [comment]
@SteveMutungi254 do you know which operations are supported on the above paths?
Can you share the docs links for these?

**Comment by irvinesunday** [comment]
Will need to add `ReadRestrictions` (`Readable = true`) annotation for the complex property `serviceProvisioningErrors` for the respective entities listed.

**Comment by SteveMutungi254** [comment]
@irvinesunday: Let's add the annotation in our internal process to help generate cmdlets.
