### ISSUE TITLE
Support for derivedTypes (...mobileApps/{id}/microsoft.graph.win32LobApp/...)

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/msgraph-metadata#434]
I believe the conversion settings that generate the openApi description may not expand paths further for navigation properties of a derived type once a odata cast paths is encountered.  

Any chance you can create a separate issue for the `/contentVersions` path and then assign it to @irvinesunday or me so this may be investigated/followed up further?

_Originally posted by @andrueastman in https://github.com/microsoftgraph/msgraph-metadata/issues/423#issuecomment-1727280918_

-----

Initial issue: I want to upload win32LobApps with the graph sdk for dotnet. I describe my process [here](https://svrooij.io/2023/08/31/publish-apps-to-intune/)

That means, creating the mobileAppContent, creating the mobileAppContentFile and eventually committing the file. All of which described in my post, is not available in the sdk.

Through using the portal I figured out that I need to change the type in the url.

I tried extending the request builders with extension methods, but they are not extendable https://github.com/microsoft/kiota-abstractions-dotnet/issues/113, which is a bummer...

Eventually @baywet pointed me to the metadata.... https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2073

I have no clue how to get these endpoints in the graph sdk, please help!

I needed these extensions for my app (and doing it this way defeats the purpose of using the sdk in my opinion.)

https://github.com/svrooij/WingetIntune/blob/30b5f76fbaa043de94be29c4c05b692b19540b0e/src/WingetIntune/Graph/GraphServiceClientExtensions.cs

and

https://github.com/svrooij/WingetIntune/blob/30b5f76fbaa043de94be29c4c05b692b19540b0e/src/WingetIntune/Graph/MobileAppsRequestBuilderExtensions.cs

**Comment by svrooij** [comment]
@andrueastman I cannot assign anyone, but here is the new issue.

**Comment by irvinesunday** [comment]
@baywet 
Changing this setting to `true` for the Kiota-based conversion setting should suffice.
![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/0bedbde3-a172-4fdc-936a-e5af7dbc0470)

We will generate the expected contained nav. props defined on the target types of the type cast segments. See the below example path:

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/603a7cd2-65b0-4122-bf16-21856796a395)

However, note that the number of paths will increase from **8,622** to **11,710** in v1.0 and **14,738** to **18,852** in Beta.
Do you think these changes will affect Kiota and the potential growth of SDKs significantly?

**Comment by baywet** [comment]
Thanks for the additional information here.
Kiota should handle the growth just fine. The SDKs I'm worried about, that's a ~50% growth.
Before we make any decision here, could we validate:
- Whether we're ONLY expanding nav props defined on the target type (and nothing defined on the base type) ?
- Whether we might have an inaccurate set of contains target true which might lead to over expansion? (lots of repeating segments at different places)

If this expansion is accurate (I suspect it isn't, and that we're probably talking about a lower growth), we might want to consider an alternative approach (leaving the setting to false, but adding some kind of annotation that'd mean "yes I really really want this one to be expanded").

**Comment by irvinesunday** [comment]
I have done a diff in v1.0 between an OpenAPI files generated with `ExpandDerivedTypesNavigationProperties = false` vis-a-vis `ExpandDerivedTypesNavigationProperties = true` and I've picked up the below nav. prop as the major cause for the blowned-up paths:

_directory/deletedItems_

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/ca6cc830-7dba-414f-9c9e-f39ea74433e7)

Removing the `DerivedTypeConstraint` from the _directory/deletedItems_ nav. prop, the total paths just increase from **8,622** to **8,641**

I need to investigate whether these type casts annotated under `deletedItems` are accurate or not.

**Comment by irvinesunday** [comment]
The type casts are valid alright, but I think that containment for `deletedItems` is wrong and needs to be removed.

**Comment by irvinesunday** [comment]
@svrooij I believe setting `ContainsTarget=false` for the `deletedItems` nav. prop. is the best route to take here.

These type cast paths, which we currently generate (with `ExpandDerivedTypesNavigationProperties = false`) will still be generated:

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/5e92f3a8-ad56-407b-922e-c679043a0f40)

Expanding on those paths is what we will be limiting (as expected).

**Comment by baywet** [comment]
Thanks for investigating. As far as I understand the ContainsTarget true is technically correct there because these objects only live in this collection (no other way to access them). BUT once they are in this collection, you can't do anything other than list/cast them and delta on the collection (you have to restore the objects before you can do anything else on them).
So I think it's safe to "fix" the ContainsTarget to false.

With that in mind, would you mind submitting a PR with the setting being changed and the XSLT to fix this contains target please?

**Comment by svrooij** [comment]
@irvinesunday technically this issue is not fixed by #442 it will need another pr to switch on the generation of the derived navigation
