### ISSUE TITLE
`POST` missing from `https://graph.microsoft.com/v1.0/external/connections/{externalConnection-id}/schema`

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-metadata#438]
The POST operation for registering a schema on an external connection is missing from our OpenAPI description.

https://learn.microsoft.com/en-us/graph/api/externalconnectors-schema-create?view=graph-rest-1.0&tabs=http

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/msgraph-metadata/pull/448

**Comment by darrelmiller** [comment]
POST is not valid for this API. Create should be performed with a PATCH. We need to update the documentation once we have identified that PATCH actually works.

**Comment by sebastienlevert** [comment]
@waldekmastykarz, can you confirm this worked for you?

**Comment by MartinM85** [comment]
I can confirm that a schema can be created with the `PATCH`.

    PATCH /v1.0/external/connections/{connection-id}/schema

returns `202` with the `Location` header.

Now, the schema can be read

    GET /v1.0/external/connections/{connection-id}/schema

even if `GET /v1.0/external/connections/{connection-id}/operations/{op-id}` returns the status `inprogress`.

Once the schema is created, update of the schema with `PATCH` works.

The `DELETE` returns `404` and `UnknownError`

**Comment by andrueastman** [comment]
Following up on the documentation fix via https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/8672

**Comment by andrueastman** [comment]
Documentation resolved via https://github.com/microsoftgraph/microsoft-graph-docs/pull/22752 and metadata https://github.com/microsoftgraph/msgraph-metadata/pull/452
