### ISSUE TITLE
Missing powershell commands for complex APIs

### ISSUE THREAD

**Issue by aimalpan** [microsoftgraph/msgraph-metadata#465]
Hi, powershell commands for the below APIs are missing in our documentation here: https://learn.microsoft.com/en-us/graph/api/resources/authenticationeventsflow?view=graph-rest-beta

Under Userflows for Azure AD for customers (Preview):

1. All APIs under Identity Providers
2. All APIs under Authentication Condition Applications
3. List attributes, add attributes and remove attributes under User flow Attributes

Attaching the screenshots for clarity:
<img width="274" alt="image" src="https://github.com/microsoftgraph/msgraph-metadata/assets/56268778/e0c3e97f-cbff-444d-9d7a-4df6a69086dd">

Could you please help generate the powershell commands for the one missing and also make sure that the example from HTTPs is translated as well?

**Comment by irvinesunday** [comment]
Here's another question regarding the path:
_/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions/applications/includeApplications/_

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/742825b2-67e4-4628-af46-20bce80633bd)

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/36cffa7b-502e-4b6a-af89-0cc2cd6b0397)

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/40403681/a92fe401-9b03-43e5-b985-1b49410232a4)

`applications` is a complex property contained in the entity type `authenticationConditions` which is the type for the complex property `conditions`. 
By adding a `ReadRestrictions` property to the complex property `conditions`, we can generate the path: _/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions_ 

However we cannot expand into the entity type of this complex property. We only expand containment navigation properties.

>Complex types are keyless [nominal](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Nominal_Types) [structured types](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Structured_Types). The lack of a key means that complex types cannot be referenced, created, updated or deleted independently of an entity type

Doc. [reference](https://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406397985)

Hence this path is not feasible: _/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/conditions/applications_

Is this a case of poor API design? 
cc: @darrelmiller @baywet

**Comment by baywet** [comment]
@irvinesunday I'm not sure I understand your comment about poor API design. Looking at this path with the metadata

```
/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/
```

for each segment we get:
- singleton of type identity identityContainer
- nav prop of type collection of authenticationEventsFlow
- indexing into the collection
- downcast to externalUsersSelfServiceSignUpEventsFlow
- property externalUsersSelfServiceSignUpEventsFlow of the cast type, of type onAuthenticationMethodLoadStartHandler
- downcast to onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp
- property identityProviders of the cast type

Which to me respects OData semantics, type cast segments are added to navigation properties so properties of the cast type can be accessed. We're never accessing a property from the base type after a type cast segment.
The only thing from our conversion conventions is that we might be inverting the indexer and type cast segments.

Did I miss anything?

**Comment by irvinesunday** [comment]
> @irvinesunday I'm not sure I understand your comment about poor API design. Looking at this path with the metadata
> 
> ```
> /identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/
> ```
> 
> for each segment we get:
> 
> * singleton of type identity identityContainer
> * nav prop of type collection of authenticationEventsFlow
> * indexing into the collection
> * downcast to externalUsersSelfServiceSignUpEventsFlow
> * property externalUsersSelfServiceSignUpEventsFlow of the cast type, of type onAuthenticationMethodLoadStartHandler
> * downcast to onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp
> * property identityProviders of the cast type
> 
> Which to me respects OData semantics, type cast segments are added to navigation properties so properties of the cast type can be accessed. We're never accessing a property from the base type after a type cast segment. The only thing from our conversion conventions is that we might be inverting the indexer and type cast segments.
> 
> Did I miss anything?

From the above clarification, to achieve the expected paths below:

1. GET _/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/_
2. POST _/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/$ref_
3. DELETE _/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/$ref_
     **Question**: Should the above path be: 
         DELETE   _/identity/authenticationEventsFlows/{authenticationEventsFlow-id}/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/{identityProviderBase-id}/$ref_
(i.e, indexing into the `identityProviders` collection before deleting the $ref)

The below annotations will need to be added:

```XML
<NavigationProperty Name="authenticationEventsFlows" Type="Collection(graph.authenticationEventsFlow)" ContainsTarget="true">
  <Annotation Term="Org.OData.Validation.V1.DerivedTypeConstraint">
    <Collection>
      <String>microsoft.graph.externalUsersSelfServiceSignUpEventsFlow</String>
    </Collection>
  </Annotation>
</NavigationProperty>
```

```XML
<EntityType Name="externalUsersSelfServiceSignUpEventsFlow" BaseType="graph.authenticationEventsFlow">
  <Property Name="onAuthenticationMethodLoadStart" Type="graph.onAuthenticationMethodLoadStartHandler">
    <Annotation Term="Org.OData.Validation.V1.DerivedTypeConstraint">
      <Collection>
        <String>microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp</String>
      </Collection>
    </Annotation>
    <Annotation Term="Org.OData.Capabilities.V1.ReadRestrictions">
      <Record>
        <PropertyValue Property="Readable" Bool="true" />
      </Record>
    </Annotation>
  </Property>
</EntityType>
```

```XML
<ComplexType Name="onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp" BaseType="graph.onAuthenticationMethodLoadStartHandler">
  <NavigationProperty Name="identityProviders" Type="Collection(graph.identityProviderBase)">
    <Annotation Term="Org.OData.Capabilities.V1.NavigationRestrictions">
      <Record>
        <PropertyValue Property="Referenceable" Bool="true" />
      </Record>
    </Annotation>
  </NavigationProperty>
</ComplexType>
```

The conversion lib will also need to be updated to retrieve complex properties of derived types. This issue will track this work: https://github.com/microsoft/OpenAPI.NET.OData/issues/437
