### ISSUE TITLE
openapi specification is missing url paths

### ISSUE THREAD

**Issue by adamijak** [microsoftgraph/msgraph-metadata#477]
`openapi/v1.0/openapi.yaml` file is missing `GET /me/drive/root` and `GET /users/{user-id}/drive/root` paths despite it is documented [here](https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http).

That probably results in this issue: microsoftgraph/msgraph-sdk-dotnet#2184

**Comment by irvinesunday** [comment]
We disabled paths after _/me/drive/..._ by removing the `drive` containment here: https://github.com/microsoftgraph/msgraph-metadata/blob/0f0d6eaa04658e49b65784f512a159e5df3317bb/transforms/csdl/preprocess_csdl.xsl#L541
The same resources should be able to be accessed via _/me/drives/{drive-id}/..._ 

However, I can see that the above paths were removed from Kiota (openapi.yaml) file by removing the `drives` containment here: https://github.com/microsoftgraph/msgraph-metadata/blob/0f0d6eaa04658e49b65784f512a159e5df3317bb/transforms/csdl/preprocess_csdl.xsl#L512

I can re-enable the containment for `drive` under users for the Kiota (openapi.yaml) file.

@andrueastman @baywet why did we remove the containment for `drives` for Kiota?

**Comment by baywet** [comment]
@irvinesunday thanks for looking into it. No we shouldn't change the containment here. The canonical path for drives is /drives/id, and any expansion should only be done under that path to avoid over expansion, and having oversized SDKs.

As for root, for the same reason, it's only going to be available in `/drives/id/root`

**Comment by irvinesunday** [comment]
Thanks for the clarification @baywet 

@adamijak you can use the canonical path to access the intended resource under `drive` as mentioned above by @baywet

**Comment by adamijak** [comment]
> Thanks for the clarification @baywet
> 
> @adamijak you can use the canonical path to access the intended resource under `drive` as mentioned above by @baywet

Yes I can, thank you.
It is shame it results in extra roundtrip.
