### ISSUE TITLE
Cloud Deployments description appended in API Ref/Graph PowerShell docs resulting in broken experience

### ISSUE THREAD

**Issue by SteveMutungi254** [microsoftgraph/msgraph-metadata#503]
**Issue Summary:**

Microsoft Graph PowerShell documentation has the appended text "_This API is supported in the following national cloud deployments_." resulting in a broken experience.

_Source_: [Get-MgApplication cmdlet](https://learn.microsoft.com/en-au/powershell/module/microsoft.graph.applications/get-mgapplication)

**Impact:** 

The appended text has nothing to do with PowerShell and mentions API and cloud deployments. The sentence also results in a "hanging" state/expectation as there is no more information on cloud deployments.

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/132555836/8ec349fd-5a34-48dd-b986-f9797766f1bc)

**Additional Information:**

The information is present in the description property in the metadata repo.

![image](https://github.com/microsoftgraph/msgraph-metadata/assets/132555836/fe80a603-bb1d-41de-9b75-6d8bb33f1212)

**Comment by SteveMutungi254** [comment]
@irvinesunday: Any joy on this?

**Comment by andrueastman** [comment]
@SteveMutungi254 We've authored https://github.com/OneDrive/apidoctor/pull/242 to fix this.
