### ISSUE TITLE
deviceManagement/managedDevices/{deviceId}/deviceCategory/$ref not present in Beta and v1.0 SDK

### ISSUE THREAD

**Issue by dansmitt** [microsoftgraph/msgraph-metadata#508]
deviceManagement/managedDevices/{deviceId}/deviceCategory/$ref not present in Beta and v1.0 SDK.

We also were not able to find documentation. However this endpoint is already in use by intune and we need to use the endpoint to automize the workflows.

**Comment by andrueastman** [comment]
The "deviceCategory" navigation property would need to have `Referencable` annotation to include this path. 

@dansmitt Any chance you can give feedback on this page on whether the documented way of creating/getting the device category is correct? 
https://learn.microsoft.com/en-us/graph/api/intune-shared-devicecategory-get?view=graph-rest-beta
https://learn.microsoft.com/en-us/graph/api/intune-shared-devicecategory-create?view=graph-rest-beta

**Comment by dansmitt** [comment]
@andrueastman Thanks for your answer. The problem is not getting or creating a device category, its the relation between a device and a device category.
