### ISSUE TITLE
Add back `deletability` support for `graph.user/photo` and `graph.group/photo`

### ISSUE THREAD

**Issue by irvinesunday** [microsoftgraph/msgraph-metadata#593]
Since `DELETE` is now supported for the above resources... we need to revert some changes made via this PR: https://github.com/microsoftgraph/msgraph-metadata/pull/392

- Initial issue: https://github.com/microsoftgraph/msgraph-metadata/issues/387
- `DELETE` support announcement: https://github.com/microsoftgraph/msgraph-metadata/issues/387#issuecomment-1764826865

- Documentation [ref](https://learn.microsoft.com/en-us/graph/api/profilephoto-delete?view=graph-rest-1.0&tabs=http#http-request): 

Related to: https://github.com/microsoftgraph/msgraph-metadata/issues/576

**Comment by shemogumbe** [comment]
I notice we still have  challenge on this, for [user photo ](https://gist.github.com/shemogumbe/33690660d1ee59f4f77b3dadac7b57fc)and [group photo](https://gist.github.com/shemogumbe/90feb0a337d7ae87fcdd69274b21169b)

This blocks us on: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2247 across SDKs

The API supports this:

1. [updating profile photo](https://gist.github.com/shemogumbe/4b73bed1ca76c88b82b87e46f4998dbb)
2. [deleting profile photo](https://gist.github.com/shemogumbe/bfb38e018e5ce15b98b8b0d2433d7ba0)

Reopening this and wishing it is prioritized as it might be a challenge to users once Exchange Online PowerShell UserPhoto cmdlets are deactivated following [this ](https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-exchange-online-powershell-userphoto-cmdlets/ba-p/3955744)

cc @irvinesunday  @adhiambovivian  @petrhollayms

**Comment by irvinesunday** [comment]
the conversion lib (Yoko) has never supported `DELETE` operations for media content paths, like the ones listed above. This might have to be a feature request on Yoko, while also considering that other non `graph.profilePhoto` _/.../$value_ paths might have the `DELETE` operations generated as well, unless there exists an appropriate annotation limiting this.

cc: @millicentachieng
