### ISSUE TITLE
Missing ability to list/discover extensions on object (e.g. email message)

### ISSUE THREAD

**Issue by Googulator** [microsoftgraph/msgraph-metadata#617]
`https://graph.microsoft.com/v1.0/users/{{userId}}/messages/{{messageId}}/extensions` throws ErrorInvalidRequest.
`https://graph.microsoft.com/v1.0/users/{{userId}}/messages/{{messageId}}?$expand=extensions` throws ErrorGraphExtensionExpandRequiresFilter, and the only acceptable filter seems to be of the form `Id eq {{extensionId}}`. (This restriction doesn't seem to be documented anywhere.)

This makes it impossible for an application to list or discover extensions on an object.

If bandwidth usage is a concern, hopefully something like `https://graph.microsoft.com/v1.0/users/{{userId}}/messages/{{messageId}}/extensions?$select=Id` or `https://graph.microsoft.com/v1.0/users/{{userId}}/messages/{{messageId}}?$expand=extensions($select=Id)` could be an acceptable solution.

**Comment by andrueastman** [comment]
Thanks for raising this @Googulator 

As this repo is mainly intended for metadata related issues, any chance you can create a request at the link below to give feedback for the API owners?

https://aka.ms/graphfeedback

**Comment by Googulator** [comment]
Submitted https://feedbackportal.microsoft.com/feedback/idea/54ed3b01-3f14-ef11-989a-6045bdbb573a on the subject.
