### ISSUE TITLE
OpenAPI Specification per Microsoft Graph Service?

### ISSUE THREAD

**Issue by haneef95** [microsoftgraph/msgraph-metadata#65]
Hi,

The [Open API Specification (OAS)/Definition here](https://github.com/microsoftgraph/msgraph-metadata/tree/master/openapi) is very useful, however, it is understandably quite large.

Are there any OAS files on a [per major service](https://docs.microsoft.com/en-us/graph/overview-major-services) basis?

Thanks 
[AB#7979](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7979)

**Comment by darrelmiller** [comment]
Yes. We have a breakdown in our PowerShell SDK.  https://github.com/microsoftgraph/msgraph-sdk-powershell/tree/dev/openApiDocs
