### ISSUE TITLE
Risky Users endpoint also returns 404

### ISSUE THREAD

**Issue by firefart** [microsoftgraph/msgraph-metadata#732]
The [`/identityProtection/riskyUsers/{riskyUserId}`](https://learn.microsoft.com/en-us/graph/api/riskyuser-get?view=graph-rest-1.0&tabs=http) endpoint also returns a 404 if the user queried was never risky. As the 404 status code is not present in the schema, the go client sdk will throw an error because this error is unexpected.

Here is an example of the response when using the batch api:
![image](https://github.com/user-attachments/assets/2c926c82-4062-4cd6-8afd-b85ad77a822a)

This behaviour can easily be triggered on the beta api in the entra id portal when viewing a user detail of such a user (the request is triggered on the overview page.)

**Comment by baywet** [comment]
Hi @firefart 
Thank you for using the SDK and for reaching out.

the get operation currently describes the following responses:


```yaml
responses:
        2XX:
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.riskyUser'
        4XX:
          $ref: '#/components/responses/error'
        5XX:
          $ref: '#/components/responses/error'
```

what do you feel is missing?

**Comment by firefart** [comment]
Hi @baywet ,
because the current golang graph sdk returns an error when checking a user that did not have a risk rating yet: `The server returned an unexpected status code and no error factory is registered for this code: 404`

The kiota error handling page https://learn.microsoft.com/en-us/openapi/kiota/errors suggests the solution, to add the code to the schema. Maybe because the 4xx is defined as an error but it's in case a not found which might be a soft error?

**Comment by baywet** [comment]
Thank you for the additional information.

The XXX error mapping [is present](https://github.com/microsoftgraph/msgraph-sdk-go/blob/83308d83754538234ef64ebf3689dbfe63af99a1/identityprotection/risky_users_risky_user_item_request_builder.go#L85), it [maps to any error status code](https://github.com/microsoft/kiota-http-go/blob/5beb0cfc3f971db7c6ff1342b22d601b04eccd30/nethttp_request_adapter.go#L785) between 400 (inclusive) and 600 (exclusive).

What would be interesting is to debug your application and step through this block to see what actually happens:
- are the mappings correctly set?
- where does the logic end up going?
- etc...

Also, please provide the go SDK version, and ensure you have the latest dependencies of the kiota / microsoft graph libraries installed.

**Comment by firefart** [comment]
Hi,
the logic is currently calling the `/riskyUsers/{UserId}` endpoint for an existing user id during a batch call and this call errors out because of the 404. I worked around that for now by doing a list query with a search for this specific UPN (which seems weird as I already know the user id).
When thinking about this I also thought that the API might be wrongly designed and should return a 200 with the no risk status for the user if the ID exists instead of a 404, but I think that's beyond this issue.

But in my case the whole batch request errors out as the 404 is unexpected in case of the API. I have not added custom error mappings, I just roll with the default config.

Versions:
```
 github.com/Azure/azure-sdk-for-go/sdk/azcore v1.16.0
github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.8.0
github.com/microsoft/kiota-abstractions-go v1.8.1
github.com/microsoftgraph/msgraph-sdk-go v1.54.0
github.com/microsoftgraph/msgraph-sdk-go-core v1.2.1
```

**Comment by baywet** [comment]
Thank you for the additional information.

Yes the support for UPNs across the API surface is inconsistent at best unfortunately... if this is a big issue for you, please open a support ticket with the service team so they fix its support for that set of operations.

Returning a 404 the the single operation follows the design guidelines.

The whole batch response failing because one of the requests returned a failed response I believe is an oversight. I'd encourage you to open a new issue at https://github.com/microsoftgraph/msgraph-sdk-go-core with as much detail as possible (example requests and responses) so we can look into that.
